### ISSUE TITLE
Environmental stuff doesn't spawn properly in Bayou

### ISSUE THREAD

**Issue by ex0planetary** [teamauroramods/BayouBlues#11]
Said stuff includes mud, cattails (I think), ducks (I think), and giant tall grass

**Comment by ShockMicro** [comment]
luckily slabfish spawn properly though

**Comment by ex0planetary** [comment]
Update: ducks should be working fine (if they aren't it's an issue with Environmental i think). Everything else needs to be added on the bayou's end though - doing now
