### ISSUE TITLE
Bayou Biome not loading on TerraForged

### ISSUE THREAD

**Issue by ninovd1** [teamauroramods/BayouBlues#24]
When you use TerraForged world type it will automatically scan for vanilla and modded biomes, in which bayou is not loading. This was checked using the /locatebiome command. Nothing after multiple tests.

**Comment by ex0planetary** [comment]
They're just really rare on TerraForged due to how that mod handles swamp biomes. Try turning up the biome weight in the config a little, should make the bayou easier to find.
