### ISSUE TITLE
Gooseberry Juice lacks bottle containers

### ISSUE THREAD

**Issue by davidjjung** [teamauroramods/BayouBlues#33]
Hiya! It seems gooseberry juice doesn't have a container, making it a bit unwieldy to use in alternative recipes. I'm guessing it might be a necessary workaround to the gooseberry jam recipe having to create three bottled foods, but I was hoping we can maybe come to a slightly more accessible solution. Thanks!

**Comment by ex0planetary** [comment]
> I'm guessing it might be a necessary workaround to the gooseberry jam recipe having to create three bottled foods
Yep, that is indeed the case. Not much we can do about this unfortunately - I'd love to change it to help datapack devs but the focus is on the base mods ofc, so it'll have to stay like this unless Mojang changes how crafting works internally.
